//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    /// <summary>
    /// Defines the names of the application permissions.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public static class Permissions
    {
        /// <summary>
        /// Provides the ability to manage security for the application.
        /// </summary>
        public const string SecurityAdministration = global::Microsoft.LightSwitch.Security.ApplicationPermissions.SecurityAdministration;
        /// <summary>
        /// Allows users to access the product catalog
        /// </summary>
        public const string CanAccessProductScreen = "LightSwitchApplication:CanAccessProductScreen";
        /// <summary>
        /// Allows users to add customers to the system
        /// </summary>
        public const string CanAddCustomer = "LightSwitchApplication:CanAddCustomer";
        /// <summary>
        /// Allows users to delete customers in the system
        /// </summary>
        public const string CanDeleteCustomer = "LightSwitchApplication:CanDeleteCustomer";
        /// <summary>
        /// Allows users to edit customers in the system
        /// </summary>
        public const string CanEditCustomer = "LightSwitchApplication:CanEditCustomer";
        /// <summary>
        /// Allows users to view customers in the system
        /// </summary>
        public const string CanViewCustomer = "LightSwitchApplication:CanViewCustomer";

        /// <summary>
        /// Gets all permissions defined for the application.  This includes system and user-defined permissions.
        /// </summary>
        public static global::System.Collections.ObjectModel.ReadOnlyCollection<string> AllPermissions { get { return global::Microsoft.LightSwitch.Security.ApplicationPermissions.AllPermissions; } }
    }
}
