

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
    public sealed partial class OrderDetail : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the OrderDetail entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OrderDetail()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public OrderDetail(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.OrderDetail> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.OrderDetail.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderDetail_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderDetail_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Id);
            }
            set
            {
                global::LightSwitchApplication.OrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Id, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Quantity
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Quantity);
            }
            set
            {
                global::LightSwitchApplication.OrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Quantity, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Quantity_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal Price
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Price);
            }
            set
            {
                global::LightSwitchApplication.OrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Price, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Price_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.CreatedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Created
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.ModifiedBy);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTimeOffset> Modified
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public byte[] RowVersion
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.RowVersion);
            }
            set
            {
                global::LightSwitchApplication.OrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.RowVersion, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RowVersion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public decimal LineItemTotal
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.LineItemTotal);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineItemTotal_Compute(ref decimal result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void LineItemTotal_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Product Product
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Product);
            }
            set
            {
                global::LightSwitchApplication.OrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Product, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Product_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.OrderHeader OrderHeader
        {
            get
            {
                return global::LightSwitchApplication.OrderDetail.DetailsClass.GetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.OrderHeader);
            }
            set
            {
                global::LightSwitchApplication.OrderDetail.DetailsClass.SetValue(this, global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.OrderHeader, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderHeader_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderHeader_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void OrderHeader_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.OrderDetail,
                global::LightSwitchApplication.OrderDetail.DetailsClass,
                global::LightSwitchApplication.OrderDetail.DetailsClass.IImplementation,
                global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass>.Entry
                __OrderDetailEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass>.Entry(
                    global::LightSwitchApplication.OrderDetail.DetailsClass.__OrderDetail_CreateNew,
                    global::LightSwitchApplication.OrderDetail.DetailsClass.__OrderDetail_Created,
                    global::LightSwitchApplication.OrderDetail.DetailsClass.__OrderDetail_AllowSaveWithErrors);
            private static global::LightSwitchApplication.OrderDetail __OrderDetail_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.OrderDetail> es)
            {
                return new global::LightSwitchApplication.OrderDetail(es);
            }
            private static void __OrderDetail_Created(global::LightSwitchApplication.OrderDetail e)
            {
                e.OrderDetail_Created();
            }
            private static bool __OrderDetail_AllowSaveWithErrors(global::LightSwitchApplication.OrderDetail e)
            {
                bool result = false;
                e.OrderDetail_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int> Quantity
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Quantity) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal> Price
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Price) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, byte[]> RowVersion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.RowVersion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, byte[]>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal> LineItemTotal
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.LineItemTotal) as global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.Product> Product
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Product) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.Product>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.OrderHeader> OrderHeader
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.OrderHeader) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.OrderHeader>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; set; }
                new int Quantity { get; set; }
                new decimal Price { get; set; }
                new string CreatedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Created { get; }
                new string ModifiedBy { get; }
                new global::System.Nullable<global::System.DateTimeOffset> Modified { get; }
                new byte[] RowVersion { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Product { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation OrderHeader { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "14.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Id_SetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Id = v;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Entry
                    Quantity = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Entry(
                        "Quantity",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Quantity_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Quantity_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Quantity_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Quantity_GetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Quantity_SetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Quantity_OnValueChanged);
                private static void _Quantity_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Quantity, sf);
                }
                private static bool _Quantity_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.Quantity_IsReadOnly(ref result);
                    return result;
                }
                private static void _Quantity_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Quantity_Validate(r);
                }
                private static int _Quantity_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.Quantity;
                }
                private static void _Quantity_SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d, int v)
                {
                    d.ImplementationEntity.Quantity = v;
                }
                private static void _Quantity_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.Quantity_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Entry
                    Price = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Entry(
                        "Price",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Price_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Price_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Price_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Price_GetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Price_SetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Price_OnValueChanged);
                private static void _Price_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Price, sf);
                }
                private static bool _Price_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.Price_IsReadOnly(ref result);
                    return result;
                }
                private static void _Price_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Price_Validate(r);
                }
                private static decimal _Price_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.Price;
                }
                private static void _Price_SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d, decimal v)
                {
                    d.ImplementationEntity.Price = v;
                }
                private static void _Price_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.Price_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static string _CreatedBy_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Created",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Created_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static string _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.ModifiedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTimeOffset> _Modified_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, byte[]>.Entry
                    RowVersion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, byte[]>.Entry(
                        "RowVersion",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._RowVersion_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._RowVersion_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._RowVersion_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._RowVersion_GetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._RowVersion_SetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._RowVersion_OnValueChanged);
                private static void _RowVersion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, byte[]>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._RowVersion, sf);
                }
                private static bool _RowVersion_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.RowVersion_IsReadOnly(ref result);
                    return result;
                }
                private static void _RowVersion_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RowVersion_Validate(r);
                }
                private static byte[] _RowVersion_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.RowVersion;
                }
                private static void _RowVersion_SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d, byte[] v)
                {
                    d.ImplementationEntity.RowVersion = v;
                }
                private static void _RowVersion_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.RowVersion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Entry
                    LineItemTotal = new global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Entry(
                        "LineItemTotal",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._LineItemTotal_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._LineItemTotal_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._LineItemTotal_ComputeValue);
                private static void _LineItemTotal_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._LineItemTotal, sf);
                }
                private static void _LineItemTotal_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.LineItemTotal_Validate(r);
                }
                private static decimal _LineItemTotal_ComputeValue(global::LightSwitchApplication.OrderDetail e)
                {
                    decimal value = default(decimal);
                    e.LineItemTotal_Compute(ref value);
                    return value;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Entry
                    Product = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Entry(
                        "Product",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_GetCoreImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_GetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_SetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_Refresh,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._Product_OnValueChanged);
                private static void _Product_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._Product, sf);
                }
                private static bool _Product_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.Product_IsReadOnly(ref result);
                    return result;
                }
                private static void _Product_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Product_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Product_GetCoreImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.Product;
                }
                private static global::LightSwitchApplication.Product _Product_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Product, global::LightSwitchApplication.Product.DetailsClass>(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Product, ref d._Product);
                }
                private static void _Product_SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d, global::LightSwitchApplication.Product v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Product, ref d._Product, (i, ev) => i.Product = ev, v);
                }
                private static void _Product_Refresh(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.Product, ref d._Product);
                }
                private static void _Product_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.Product_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.OrderHeader>.Entry
                    OrderHeader = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.OrderHeader>.Entry(
                        "OrderHeader",
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_Stub,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_ComputeIsReadOnly,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_Validate,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_GetCoreImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_GetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_SetImplementationValue,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_Refresh,
                        global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties._OrderHeader_OnValueChanged);
                private static void _OrderHeader_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.OrderDetail.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.OrderHeader>.Data> c, global::LightSwitchApplication.OrderDetail.DetailsClass d, object sf)
                {
                    c(d, ref d._OrderHeader, sf);
                }
                private static bool _OrderHeader_ComputeIsReadOnly(global::LightSwitchApplication.OrderDetail e)
                {
                    bool result = false;
                    e.OrderHeader_IsReadOnly(ref result);
                    return result;
                }
                private static void _OrderHeader_Validate(global::LightSwitchApplication.OrderDetail e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.OrderHeader_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _OrderHeader_GetCoreImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.ImplementationEntity.OrderHeader;
                }
                private static global::LightSwitchApplication.OrderHeader _OrderHeader_GetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.OrderHeader, global::LightSwitchApplication.OrderHeader.DetailsClass>(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.OrderHeader, ref d._OrderHeader);
                }
                private static void _OrderHeader_SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass d, global::LightSwitchApplication.OrderHeader v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.OrderHeader, ref d._OrderHeader, (i, ev) => i.OrderHeader = ev, v);
                }
                private static void _OrderHeader_Refresh(global::LightSwitchApplication.OrderDetail.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.OrderDetail.DetailsClass.PropertySetProperties.OrderHeader, ref d._OrderHeader);
                }
                private static void _OrderHeader_OnValueChanged(global::LightSwitchApplication.OrderDetail e)
                {
                    e.OrderHeader_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, int>.Data _Quantity;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Data _Price;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, string>.Data _ModifiedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::System.Nullable<global::System.DateTimeOffset>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, byte[]>.Data _RowVersion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityComputedProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, decimal>.Data _LineItemTotal;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.Product>.Data _Product;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.OrderDetail, global::LightSwitchApplication.OrderDetail.DetailsClass, global::LightSwitchApplication.OrderHeader>.Data _OrderHeader;
            
        }
    
        #endregion
    }
    
    #endregion
}
